config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get '/home/about' => 'homes#about'
  resources :books

  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :books , dependent: :destroy

  validates :name, presence: true, length: { minimum: 2,maximum: 20}, uniqueness: true
  validates :introduction, length: { maximum: 50}




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters,if: :devise_controller?

    def after_sign_out_path_for(resource)
      root_path
    end
    def after_sign_in_path_for(resource)
	  user_path(resource)
    end

  private
	def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:sign_up, keys:[:email])
	  #devise_parameter_sanitizer.permit(:sign_in, keys:[:name])
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, {only: [:update, :destroy]}

  def new
    @book = Book.new
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="You have creatad book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:notice]="Book was successfully destroyed."
      redirect_to books_path
    end
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end

    def correct_user
    @book = Book.find(params[:id])
     if @book.user_id != current_user.id

       redirect_to books_path
     end
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def new
  end

  def create
  end

  def index
  end

  def show
  end

  def destroy
  end
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    # １. データを新規登録するためのインスタンス作成
    book = Book.new(book_params)
    # ２. データをデータベースに保存するためのsaveメソッド実行
    book.save
    # ３. トップ画面へリダイレクト
    redirect_to '/top'
  end

  private
  # ストロングパラメータ
  def list_params
    params.require(:list).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


 def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.where(user_id:@user.id)

 end

 def create
    @user = User.new(user_params)
    if @user.save
       flash[:notice] = "successfully"
    end
 end


 def edit
    @user = User.find(params[:id])
    if @user == current_user

      render :edit
    else
      redirect_to user_path(current_user)
    end
 end

 def index
     @users = User.all
     @user = current_user
     @newbook = Book.new
 end

 def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(current_user)
    else
      render :edit
    end
 end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  def correct_user
    @user = User.find(params[:id])
    if current_user != @user.id
       redirect_to user_path(current_user)
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div class="error">
      <h3><%= @book.errors.count %> errors prohibited this book from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
<div class="container">
 <div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <h1>Editing Book</h1>
    <div class="menu">]
     <thead>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
     </thead>
      <%= link_to "Show", book_path(@book) %>
      <%= link_to "Back", books_path %>
    </div>
  <% end %>
  <div class="form-title">Title</div>
    <%= f.text_field :title %>
  <div class="form-body">Opinion</div>
    <%= f.text_area :body %><br>
  <div class="upload">
    <%= f.submit " Update Book" %>
  </div>
  <% end %>
  <div class="menu">
   <%= link_to "Show", book_path(@book) %>
   <%= link_to "Back", books_path %>
  </div>
  <div class="col-xs-3"></div>
  </div>
 </div>

 <footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
 </footer>
</div>

app/views/books/index.html.erb
<div class="container">
 <div class="row">
    <div class="col-md-3">
  <%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div class="error">
      <h3><%= @book.errors.count %> errors prohibited this book from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>
  <% end %>

  <h2>User info</h2>
     <thead>
       <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg",size:'50x50' %>
       <th>name</th>
       <h3><%= @user.name %></h3>
       <th>introduction	</th>
       <th><%= @user.introduction %></th>
      <li>
       <% if @user.id == current_user.id %>
        <p><%= link_to "", edit_user_path(@user), class: "fas fa-user-cog" %></p>
       <% end %>
      </li>
     </thead>

      <h2>New book</h2>
      <%= form_with model: @book, url: books_path, local:true do |f| %>
      <h4>タイトル</h4>
       <%= f.text_field :title %>
      <h4>本文</h4>
       <%= f.text_area :body %>
       <%= f.submit 'Create Book' %>
       <% end %>
       </div>

 <div class="col-md-8 offset-md-1">
  <table class="table table-user-show">
    <%= form_with model:@book, local:true do |f| %>
      <h2>Books</h2>
       <thead>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
       </thead>
    <% end %>
   <tbody>
    <% @books.each do |book| %>
      <tr>
       <td>
        <%= link_to user_path(book) do %>
        <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50,fallback: "no_image.jpg",size:'50x50'%>
        <% end %>
       </td>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
      </tr>
    <% end %>
   </tbody>
  </table>
 </div>
  </div>
</div>

  <footer>
   <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
   </div>
  </footer>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
  <div class="col-md-3">
    <h2>User info</h2>
     <thead>
       <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg",size:'50x50' %>
       <th>name</th>
       <h3><%= @user.name %></h3>
       <th>introduction	</th>
       <th><%= @user.introduction %></th>
      <li>
       <%# if @user.id == current_user.id %>
        <p><%= link_to "", edit_user_path(@user), class: "fas fa-user-cog" %></p>
       <%# end %>
      </li>
     </thead>
    <h2>New book</h2>
       <%= form_with model: @newbook, url:'/books', local:true do |f| %>
      <h4>タイトル</h4>
       <%= f.text_field :title %>
      <h4>本文</h4>
       <%= f.text_area :body %>
       <%= f.submit 'Create Book' %>
       <% end %>
  </div>

  <div class="col-md-8 offset-md-1">
    <h1>Book detail</h1>
      <table class="table table-user-show">

        <tr>
          <td><%= attachment_image_tag @book.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg",size:'50x50' %></td>
          <td><%= link_to @user.name, user_path(@book.user_id) %></td>
          <td><%= link_to @book.title, book_path(@book.id) %></td>
          <td><%= @book.body %></td>
          <% if @book.user_id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-success"%></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-danger" %></td>
          <% end %>
        </tr>
      </table>
  </div>
 </div>
</div>

app/views/homes/about.html.erb
<!DOCTYPE html>
<html>
 <main>
   <p id="notice"></p>
   <div class='container'>
   <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
   </div>
   </div>

 </main>
  <footer>
    <div class='container mt-5'>
    <div class='row'>
    <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>
  </body>
</html>

app/views/homes/top.html.erb
<head>
    <title>Bookers2-debug</title>
    <meta name="csrf-param" content="authenticity_token" />
    <meta name="csrf-token" content="67UCwY4nkpGRQoAGkorx+vjyfy0Vgz4Ig3qHnvcrAHzMNgvYe1dwt14qgS1ZOGUyvVrBd4ahnQQcdKFFyC7lOA==" />

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" media="all" href="/assets/application-16605eadccf37c23d1fa922dd614f45b9f2cf25723e2e4032f1975b02ea7d11f.css" data-turbolinks-track="reload" />
    <script src="/assets/application-3ac47b8571e58aab844e8d0a988f0f55d8a16c1a75953470343f79cf1bec8528.js" data-turbolinks-track="reload"></script>
</head>

<body>
 <main>
  <p id="notice"></p>
   <div class="container">
    <div class="row">
     <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
     </div>
    </div>
   </div>
 </main>

 <footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
 </footer>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <header>
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <% if user_signed_in? %>
       <li><%= link_to "Bookers", user_path(current_user.id), class: "navbar-brand" %></li>
      <% else %>
       <li><%= link_to "Bookers", root_path, class: "navbar-brand" %></li>
      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
           <li><%= link_to "Home", user_path(current_user.id), class: "fas fa-home nav-link text-light" %></li>
           <li><%= link_to "Users", users_path, class: "fas fa-users nav-link text-light" %></li>
           <li><%= link_to "Books", books_path, class: "fas fa-book-open nav-link text-light" %></li>
           <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %></li>
          <% else %>
           <li><%= link_to "Home", root_path, class: "fas fa-home nav-link text-light" %></li>
           <li><%= link_to "About", home_about_path, class: "fas fa-link nav-link text-light" %></li>
           <li><%= link_to "Sign up",  new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %></li>
           <li><%= link_to "Log in", user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %></li>
          <% end %>
        </ul>
      </div>
    </div>
   </nav>
  </header>

  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark">
      <div class="nav navbar-left">
        <h3><p class="text-white">Bookers</p></h3>
      </div>
      <ul class="nav navbar-nav navbar-right">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
      </ul>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/todolists/new.html.erb
 <h2>New book</h2>
     <h1>新規投稿</h1>
       <%= form_with model: @book, url:'/todolists', local:true do |f| %>
      <h4>タイトル</h4>
       <%= f.text_field :title %>
      <h4>本文</h4>
       <%= f.text_area :body %>
       <%= f.submit '投稿' %>
       <% end %>

app/views/users/edit.html.erb
<h1>User info</h1>
 <%= form_with model:@user, local:true do |f| %>
  <% if @user.errors.any? %>
    <div class="error">
      <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="user-name">Name</div>
    <%= f.text_field :name %>
  <div class="user-edit-image">Image</div>
    <%= f.attachment_field :profile_image %>
  <div class="form-body">Introduction</div>
    <%= f.text_area :introduction %><br>
  <div class="upload">
    <%= f.submit " Update User" %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-3">
    <h2>User info</h2>
     <thead>
       <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg",size:'50x50' %>
       <th>name</th>
       <h3><%= @user.name %></h3>
       <th>introduction	</th>
       <th><%= @user.introduction %></th>
      <li>
       <% if @user.id = current_user.id %>
        <p><%= link_to "", edit_user_path(@user), class: "fas fa-user-cog" %></p>
       <% end %>
      </li>
     </thead>
    <h2>New book</h2>
       <%= form_with model: @newbook, url:'/books', local:true do |f| %>
      <h4>タイトル</h4>
       <%= f.text_field :title %>
      <h4>本文</h4>
       <%= f.text_area :body %>
       <%= f.submit 'Create Book' %>
       <% end %>
  </div>


 <div class="col-md-8 offset-md-1">
  <table class="table table-sm user-index">
    <h2>Users</h2>
     <thead>
       <th>image</th>
       <th>name</th>
       <th></th>
     </thead>

  <tbody>
    <% @users.each do |user| %>
     <tr>
       <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50,fallback: "no_image.jpg",size:'50x50' %></td>
       <td><%= user.name %></td>
       <td><%= link_to "Show", "/users/#{user.id}" %></td>
     </tr>
  	 <% end %>
  </tbody>
  </table>
 </div>
</div>


 <footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
 </footer>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
    <% if @user.id==current_user.id %>
  　　<% link_to("編集", "users/#{@user.id}/edit") %>
　　<% end %>

      <h2>User info</h2>
     <thead>
       <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg",size:'50x50' %>
       <th>name</th>
       <h3><%= @user.name %></h3>
       <th>introduction	</th>
       <th><%= @user.introduction %></th>
      <li>
       <p><%= link_to "", edit_user_path(@user), class: "fas fa-user-cog" %></p>
      </li>
     </thead>

     <h2>New book</h2>
       <%= form_with model: @book, url: books_path, method:"post", local:true do |f| %>
      <h4>Title</h4>
       <%= f.text_field :title %>
      <h4>Opinion</h4>
       <%= f.text_area :body %>
       <%= f.submit 'Create Book' %>
       <% end %>
    </div>
 <div class="col-md-8 offset-md-1">
   <table class="table table-user-show">
      <h1>Books</h1>
        <thead>
         <th></th>
         <th>Title</th>
         <th>Opinion</th>
        </thead>
       <% @books.each do |book| %>
      <tr>
       <td>
        <%= link_to  user_path(@user) do %>
        <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50,fallback: "no_image.jpg",size:'50x50'%>
        <% end %>
       </td>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
      </tr>
        <% end %>
      </table>
    </div>
  </div>

  <footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
 </footer>
</div>